<style>
.jp-Notebook, .jp-RenderedHTMLCommon, .rendered_html, .rendered_html table, .rendered_html th, .rendered_html td { font-family: "Microsoft YaHei", "Microsoft JhengHei", "SimHei", "SimSun", "Noto Sans CJK SC", "PingFang SC", Arial, sans-serif !important; }
.rendered_html table { font-size: 13px; }
.rendered_html td { vertical-align: top; }
</style>
# 10人persona问卷作答：有/无背景信息影响分析

本 notebook 对同一批随机抽取的10位CFPS persona进行比较：一版不提供竞品/产品背景信息，一版提供整理后的 Markdown 背景信息。

## 1. 结论导读

- 本 notebook 不嵌入静态SVG；图表由后续代码单元运行生成。
- 重点不再只是运行时间，而是比较背景信息如何改变具体题目答案、哪些persona更容易变化，以及变化集中在哪些问卷模块。
- `comparison_top10_changed_answer_details.csv` 保存了Top变化题目的逐人答案对照和人口学信息。

## 2. 运行状态

| variant_label | status | 人数 |
| --- | --- | --- |
| 不含背景信息 | ok | 10 |
| 含背景信息 | ok | 10 |

## 3. 10位persona人口学与健康画像

| 样本编号 | 年龄 | 性别 | 省份 | 城乡属性 | 学历 | BMI | BMI配额段 | 目标人群细分 | 合并症类别汇总 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 47 | 32 | 女 | 吉林省 | 城镇 | 大学本科 | 28.04 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 关节运动系统 |
| 51 | 49 | 女 | 河南省 | 城镇 | 高中/中专/技校/职高 | 30.85 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 |
| 86 | 61 | 女 | 上海市 | 城镇 | 高中/中专/技校/职高 | 33.3 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 |
| 120 | 55 | 男 | 河南省 | 城镇 | 大学本科 | 24.22 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 |
| 123 | 45 | 男 | 湖北省 | 城镇 | 大学本科 | 24.51 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压；心脑血管 |
| 138 | 34 | 男 | 山东省 | 城镇 | 大学本科 | 24.84 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 |
| 150 | 32 | 男 | 黑龙江省 | 城镇 | 大学本科 | 27.13 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 肝病或MASH线索 |
| 151 | 52 | 男 | 广西壮族自治区 | 城镇 | 高中/中专/技校/职高 | 26.35 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 |
| 187 | 47 | 男 | 河南省 | 城镇 | 大学本科 | 26.73 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 |
| 207 | 55 | 男 | 河南省 | 城镇 | 高中/中专/技校/职高 | 28.55 | 肥胖_BMI>28 | 肥胖且合并糖尿病 | 糖尿病 |

## 4. 每位persona受背景影响的题目数量

| pid | 样本编号 | 年龄 | 性别 | 省份 | 城乡属性 | 学历 | BMI | BMI配额段 | 目标人群细分 | 合并症类别汇总 | 变化题目数 | Persona生成线索 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 220322103 | 47 | 32 | 女 | 吉林省 | 城镇 | 大学本科 | 28.04 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 关节运动系统 | 44 | 32岁女，吉林省城镇，BMI 28.04（肥胖），大学本科，收入近似为1.7万-5万，合并症线索：关节运动系统，自评健康很健康，从不锻炼。 |
| 673100701 | 138 | 34 | 男 | 山东省 | 城镇 | 大学本科 | 24.84 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | 43 | 34岁男，山东省城镇，BMI 24.84（超重），大学本科，收入近似为1.7万-5万，合并症线索：关节运动系统，自评健康比较健康，低频锻炼。 |
| 411879101 | 120 | 55 | 男 | 河南省 | 城镇 | 大学本科 | 24.22 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | 39 | 55岁男，河南省城镇，BMI 24.22（超重），大学本科，收入近似为5万-10万，合并症线索：高血压，自评健康比较健康，规律锻炼。 |
| 411244104 | 51 | 49 | 女 | 河南省 | 城镇 | 高中/中专/技校/职高 | 30.85 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | 36 | 49岁女，河南省城镇，BMI 30.85（肥胖），高中/中专/技校/职高，收入近似为1.7万-5万，合并症线索：无可识别研究相关合并症，自评健康一般，规律锻炼。 |
| 310855102 | 86 | 61 | 女 | 上海市 | 城镇 | 高中/中专/技校/职高 | 33.3 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | 34 | 61岁女，上海市城镇，BMI 33.30（肥胖），高中/中专/技校/职高，收入近似为1.7万-5万，合并症线索：无可识别研究相关合并症，自评健康比较健康，从不锻炼。 |
| 450250102 | 151 | 52 | 男 | 广西壮族自治区 | 城镇 | 高中/中专/技校/职高 | 26.35 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | 34 | 52岁男，广西壮族自治区城镇，BMI 26.35（超重），高中/中专/技校/职高，收入近似为1.7万-5万，合并症线索：关节运动系统，自评健康很健康，高频锻炼。 |
| 420493101 | 123 | 45 | 男 | 湖北省 | 城镇 | 大学本科 | 24.51 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压；心脑血管 | 33 | 45岁男，湖北省城镇，BMI 24.51（超重），大学本科，收入近似为10万以上，合并症线索：高血压；心脑血管，自评健康比较健康，规律锻炼。 |
| 411875101 | 187 | 47 | 男 | 河南省 | 城镇 | 大学本科 | 26.73 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | 24 | 47岁男，河南省城镇，BMI 26.73（超重），大学本科，收入近似为5万-10万，合并症线索：高血压，自评健康比较健康，规律锻炼。 |
| 411313102 | 207 | 55 | 男 | 河南省 | 城镇 | 高中/中专/技校/职高 | 28.55 | 肥胖_BMI>28 | 肥胖且合并糖尿病 | 糖尿病 | 24 | 55岁男，河南省城镇，BMI 28.55（肥胖），高中/中专/技校/职高，收入近似为5万-10万，合并症线索：糖尿病，自评健康比较健康，高频锻炼。 |
| 211769103 | 150 | 32 | 男 | 黑龙江省 | 城镇 | 大学本科 | 27.13 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 肝病或MASH线索 | 22 | 32岁男，黑龙江省城镇，BMI 27.13（超重），大学本科，收入近似为1.7万-5万，合并症线索：肝病或MASH线索，自评健康比较健康，从不锻炼。 |

## 5. 分人群变化概览

| 性别 | BMI配额段 | 目标人群细分 | 人数 | 平均变化题目数 | 最高变化题目数 |
| --- | --- | --- | --- | --- | --- |
| 女 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 3 | 38.0 | 44 |
| 男 | 肥胖_BMI>28 | 肥胖且合并糖尿病 | 1 | 24.0 | 24 |
| 男 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 6 | 32.5 | 43 |

## 6. 运行耗时与token

| 版本 | 人数 | 失败人数 | 画像平均秒 | 问卷平均秒 | 画像总tokens | 问卷总tokens | 总tokens |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 不含背景信息 | 10 | 0 | 14.81 | 47.94 | 30078 | 265401 | 295479 |
| 含背景信息 | 10 | 0 | 15.979 | 55.657 | 48998 | 287147 | 336145 |

## 7. Top变化问题总览

| 题目ID | 问卷部分 | 题型 | 答案变化人数 | 答案变化率 | 主要答案迁移 | 题目文本 |
| --- | --- | --- | --- | --- | --- | --- |
| A6 | A 减重旅程 | matrix_numeric | 10 | 1.0 | {"2":{"attempts":3,"avg_months":3,"monthly_cost_rmb":200},"4":{"attempts":2,"avg_months":2,"monthly_cost_rmb":300},"9":{"attempts":3,"avg_months":2,"monthly_cost_rmb":0},"10":{"attempts":1,"avg_months":1.5,"monthly_cost_rmb":200}} -> {"2":{"attempts":3,"avg_months":3,"monthly_cost_rmb":300},"4":{"attempts":2,"avg_months":2,"monthly_cost_rmb":200},"9":{"attempts":3,"avg_months":2.5,"monthly_cost_rmb":0},"11":{"attempts":1,"avg_months":3,"monthly_cost_rmb":400}}（1人）；{"2":{"attempts":3,"avg_months":4,"monthly_cost_rmb":300},"3":{"attempts":2,"avg_months":2,"monthly_cost_rmb":150},"4":{"attempts":1,"avg_months":1,"monthly_cost_rmb":200},"9":{"attempts":3,"avg_months":3,"monthly_cost_rmb":0},"12":{"attempts":1,"avg_months":2,"monthly_cost_rmb":400}} -> {"2":{"attempts":3,"avg_months":3.0,"monthly_cost_rmb":300},"4":{"attempts":2,"avg_months":2.0,"monthly_cost_rmb":200},"9":{"attempts":3,"avg_months":2.0,"monthly_cost_rmb":0},"12":{"attempts":1,"avg_months":1.0,"monthly_cost_rmb":400},"13":{"attempts":1,"avg_months":3.0,"monthly_cost_rmb":1500}}（1人）；{"2":{"attempts":3,"avg_months":6,"monthly_cost_rmb":200},"3":{"attempts":2,"avg_months":2,"monthly_cost_rmb":150},"4":{"attempts":2,"avg_months":3,"monthly_cost_rmb":200},"5":{"attempts":1,"avg_months":2,"monthly_cost_rmb":300},"9":{"attempts":4,"avg_months":6,"monthly_cost_rmb":0}} -> {"2":{"attempts":3,"avg_months":6,"monthly_cost_rmb":200},"4":{"attempts":2,"avg_months":3,"monthly_cost_rmb":300},"9":{"attempts":4,"avg_months":6,"monthly_cost_rmb":0},"12":{"attempts":1,"avg_months":2,"monthly_cost_rmb":150},"13":{"attempts":1,"avg_months":4,"monthly_cost_rmb":800}}（1人） | 针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。 |
| B19 | B GLP-1药物选择与使用情况 | matrix_rating_1_7 | 10 | 1.0 | {"A":{"0":5,"1":5,"2":6,"3":4,"4":3,"5":5,"6":5,"7":5,"8":4,"9":5,"10":5,"11":4,"12":4,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":4,"20":3}} -> {}（1人）；{"A":{"0":5,"1":5,"2":6,"3":4,"4":3,"5":5,"6":5,"7":5,"8":4,"9":5,"10":5,"11":4,"12":4,"13":6,"14":5,"15":6,"16":6,"17":3,"18":5,"19":4,"20":3}} -> {"A":{"0":5,"1":5,"2":6,"3":4,"4":3,"5":5,"6":6,"7":5,"8":4,"9":5,"10":5,"11":4,"12":4,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":4,"20":3}}（1人）；{"A":{"0":5,"1":5,"2":6,"3":4,"4":3,"5":5,"6":6,"7":5,"8":4,"9":5,"10":5,"11":4,"12":4,"13":6,"14":5,"15":6,"16":6,"17":4,"18":5,"19":4,"20":3}} -> {"A":{"0":5,"1":5,"2":6,"3":4,"4":3,"5":5,"6":6,"7":5,"8":4,"9":5,"10":5,"11":4,"12":4,"13":6,"14":5,"15":6,"16":6,"17":3,"18":5,"19":4,"20":3}}（1人） | 结合实际使用体验，对使用过的GLP-1药物在各维度表现的满意度打分。 |
| C1 | C 新产品测试 | matrix_rating_1_7 | 10 | 1.0 | {"X":{"1":5,"2":5,"3":5,"4":5,"5":3,"6":5},"A":{"1":6,"2":5,"3":6,"4":6,"5":4,"6":6},"B":{"1":5,"2":5,"3":5,"4":5,"5":4,"6":5},"C":{"1":5,"2":5,"3":5,"4":5,"5":3,"6":5}} -> {"X":{"1":5,"2":5,"3":5,"4":6,"5":3,"6":5},"A":{"1":6,"2":5,"3":7,"4":6,"5":4,"6":6},"B":{"1":6,"2":6,"3":5,"4":5,"5":4,"6":6},"C":{"1":6,"2":5,"3":6,"4":5,"5":3,"6":5}}（1人）；{"X":{"1":5,"2":5,"3":5,"4":5,"5":3,"6":5},"A":{"1":6,"2":5,"3":6,"4":6,"5":4,"6":6},"B":{"1":6,"2":6,"3":5,"4":5,"5":4,"6":5},"C":{"1":5,"2":5,"3":5,"4":5,"5":3,"6":5}} -> {"X":{"1":5,"2":5,"3":5,"4":6,"5":3,"6":5},"A":{"1":6,"2":5,"3":6,"4":6,"5":4,"6":6},"B":{"1":6,"2":5,"3":5,"4":5,"5":4,"6":5},"C":{"1":6,"2":5,"3":6,"4":6,"5":3,"6":6}}（1人）；{"X":{"1":5,"2":5,"3":5,"4":5,"5":3,"6":5},"A":{"1":6,"2":5,"3":7,"4":6,"5":4,"6":6},"B":{"1":6,"2":5,"3":5,"4":5,"5":4,"6":5},"C":{"1":5,"2":5,"3":6,"4":5,"5":3,"6":5}} -> {"X":{"1":5,"2":5,"3":5,"4":6,"5":3,"6":5},"A":{"1":6,"2":5,"3":7,"4":6,"5":4,"6":6},"B":{"1":6,"2":5,"3":5,"4":5,"5":4,"6":5},"C":{"1":6,"2":5,"3":6,"4":5,"5":3,"6":5}}（1人） | 阅读产品X、产品A、产品B、产品C信息后，对各药物在各维度上的表现满意度和总体满意度分别打分。 |
| B10 | B GLP-1药物选择与使用情况 | matrix_multi_plus_single | 9 | 0.9 |  -> {"3":{"all_reasons":[2,4],"most_important":4}}（1人）； -> {"3":{"all_reasons":[5,4],"most_important":5}}（1人）；{"3":{"all_reasons":[2,4],"most_important":4}} -> {}（1人） | 既往使用过但目前已停用的GLP-1药物，停药原因分别是什么？最重要原因是什么？ |
| B13 | B GLP-1药物选择与使用情况 | matrix_multi | 9 | 0.9 | {"A":[1,2,5,6,7,15]} -> {"A":[1,5,7,8,15]}（1人）；{"A":[1,2,5,7,15]} -> {"A":[1,2,6,7,15]}（1人）；{"A":[1,2,6,7,15]} -> （1人） | 选择相关GLP-1时，您从哪些信息渠道获取过产品信息？ |
| B14 | B GLP-1药物选择与使用情况 | matrix_titration | 9 | 0.9 | {} -> {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":16,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":24}}（2人）；{"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":12,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":20}} -> {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1mg","maintenance_weeks":8,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":16}}（1人）；{"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":16,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":24}} -> {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":20,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":28}}（1人） | 回忆GLP-1实际使用过程中的剂量调整过程：起始剂量、维持剂量、过渡剂量及各阶段持续周数。 |
| B16 | B GLP-1药物选择与使用情况 | matrix | 9 | 0.9 | {"A":{"used_tool":2,"satisfaction":"","most_helpful_feature":""}} -> {"A":{"used_tool":2,"satisfaction":"","most_helpful_feature":""},"B":{"used_tool":2,"satisfaction":"","most_helpful_feature":""},"C":{"used_tool":2,"satisfaction":"","most_helpful_feature":""}}（2人）；{} -> {"A":{"used_tool":2,"satisfaction":"","most_helpful_feature":""}}（2人）；{"A":{"used_tool":1,"satisfaction":6,"most_helpful_feature":"用药提醒和记录体重变化的功能"}} -> {"A":{"used_tool":1,"satisfaction":6,"most_helpful_feature":"用药提醒和记录体重变化的功能比较有帮助。"}}（1人） | 是否借助厂家提供的小程序作为用药记录、提醒和指南支持工具？满意度如何？最有帮助的功能是什么？ |
| B17 | B GLP-1药物选择与使用情况 | matrix_numeric | 9 | 0.9 | {} -> {"3":{"loss_kg":6}}（3人）；{"3":{"loss_kg":5}} -> （1人）；{"3":{"loss_kg":5}} -> {"3":{"loss_kg":6}}（1人） | 使用各GLP-1药物后，体重下降了多少kg？ |
| B18 | B GLP-1药物选择与使用情况 | matrix_numeric | 9 | 0.9 |  -> {"3":{"rebounded":1,"rebound_kg":2}}（2人）；{"3":{"rebounded":1,"rebound_kg":2}} -> {"3":{"rebounded":1,"rebound_kg":3}}（2人）；{} -> {"3":{"rebounded":1,"rebound_kg":3}}（2人） | 停止使用各GLP-1药物后，是否经历体重反弹？若经历，反弹多少kg？ |
| B3 | B GLP-1药物选择与使用情况 | matrix_rating_1_7 | 9 | 0.9 | {"1":6,"2":7,"3":5,"4":6,"5":5,"6":6,"7":6,"8":5,"9":6,"10":4,"11":6,"12":6,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":6,"20":5} -> {"1":6,"2":7,"3":5,"4":6,"5":5,"6":6,"7":6,"8":5,"9":6,"10":5,"11":5,"12":5,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":5,"20":4}（1人）；{"1":6,"2":7,"3":5,"4":6,"5":5,"6":6,"7":6,"8":5,"9":6,"10":5,"11":6,"12":6,"13":5,"14":5,"15":5,"16":6,"17":4,"18":5,"19":6,"20":5} -> {"1":6,"2":7,"3":5,"4":6,"5":5,"6":6,"7":6,"8":5,"9":6,"10":5,"11":6,"12":6,"13":5,"14":5,"15":5,"16":6,"17":4,"18":5,"19":6,"20":5}（1人）；{"1":6,"2":7,"3":5,"4":6,"5":5,"6":6,"7":6,"8":5,"9":6,"10":5,"11":6,"12":6,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":6,"20":5} -> {"1":6,"2":7,"3":5,"4":6,"5":5,"6":6,"7":6,"8":4,"9":6,"10":5,"11":6,"12":6,"13":5,"14":5,"15":5,"16":6,"17":4,"18":5,"19":5,"20":4}（1人） | 选择GLP-1作为减重治疗药物时，以下考虑因素的重要程度分别如何？ |
| B9 | B GLP-1药物选择与使用情况 | matrix | 9 | 0.9 | {"1":{"used":2,"status":"","start_year_month":""},"2":{"used":2,"status":"","start_year_month":""},"3":{"used":1,"status":1,"start_year_month":"2024-01"},"4":{"used":2,"status":"","start_year_month":""},"5":{"used":2,"status":"","start_year_month":""},"6":{"used":2,"status":"","start_year_month":""}} -> {"1":{"used":2,"status":"","start_year_month":""},"2":{"used":2,"status":"","start_year_month":""},"3":{"used":1,"status":2,"start_year_month":"2023-03"},"4":{"used":2,"status":"","start_year_month":""},"5":{"used":2,"status":"","start_year_month":""},"6":{"used":2,"status":"","start_year_month":""}}（2人）；{"1":{"used":2,"status":"","start_year_month":""},"2":{"used":2,"status":"","start_year_month":""},"3":{"used":2,"status":"","start_year_month":""},"4":{"used":2,"status":"","start_year_month":""},"5":{"used":2,"status":"","start_year_month":""},"6":{"used":2,"status":"","start_year_month":""}} -> {"1":{"used":2,"status":"","start_year_month":""},"2":{"used":2,"status":"","start_year_month":""},"3":{"used":1,"status":2,"start_year_month":"2023-03"},"4":{"used":2,"status":"","start_year_month":""},"5":{"used":2,"status":"","start_year_month":""},"6":{"used":2,"status":"","start_year_month":""}}（2人）；{"1":{"used":2,"status":"","start_year_month":""},"2":{"used":2,"status":"","start_year_month":""},"3":{"used":1,"status":2,"start_year_month":"2023-03"},"4":{"used":2,"status":"","start_year_month":""},"5":{"used":2,"status":"","start_year_month":""},"6":{"used":2,"status":"","start_year_month":""}} -> {"1":{"used":2,"status":"","start_year_month":""},"2":{"used":2,"status":"","start_year_month":""},"3":{"used":1,"status":2,"start_year_month":"2023-06"},"4":{"used":2,"status":"","start_year_month":""},"5":{"used":2,"status":"","start_year_month":""},"6":{"used":2,"status":"","start_year_month":""}}（1人） | 请勾选既往使用过的GLP-1药物品牌，并填写当前使用状态和启用时间。 |
| C4_C5 | C 商品名测试 | matrix_rating_1_7 | 9 | 0.9 | {"1":{"readability":5,"memorability":5},"2":{"readability":4,"memorability":4},"3":{"readability":4,"memorability":4},"4":{"readability":5,"memorability":5},"5":{"readability":3,"memorability":3},"6":{"readability":5,"memorability":5}} -> {"1":{"readability":5,"memorability":5},"2":{"readability":4,"memorability":4},"3":{"readability":4,"memorability":4},"4":{"readability":5,"memorability":5},"5":{"readability":4,"memorability":4},"6":{"readability":5,"memorability":5}}（1人）；{"1":{"readability":5,"memorability":5},"2":{"readability":4,"memorability":4},"3":{"readability":4,"memorability":4},"4":{"readability":5,"memorability":5},"5":{"readability":4,"memorability":4},"6":{"readability":5,"memorability":5}} -> {"1":{"readability":5,"memorability":5},"2":{"readability":4,"memorability":4},"3":{"readability":5,"memorability":5},"4":{"readability":5,"memorability":4},"5":{"readability":4,"memorability":4},"6":{"readability":5,"memorability":5}}（1人）；{"1":{"readability":5,"memorability":5},"2":{"readability":4,"memorability":4},"3":{"readability":5,"memorability":5},"4":{"readability":5,"memorability":4},"5":{"readability":4,"memorability":4},"6":{"readability":5,"memorability":5}} -> {"1":{"readability":5,"memorability":5},"2":{"readability":4,"memorability":4},"3":{"readability":4,"memorability":4},"4":{"readability":5,"memorability":5},"5":{"readability":4,"memorability":4},"6":{"readability":5,"memorability":5}}（1人） | 对各GLP-1药物商品名的易读性和好记程度打分。 |
| C6 | C 商品名测试 | matrix_rating_1_7 | 9 | 0.9 | {"1":5,"2":5,"3":4,"4":5,"5":4,"6":5} -> {"1":5,"2":5,"3":5,"4":5,"5":4,"6":5}（2人）；{"1":5,"2":6,"3":5,"4":5,"5":4,"6":5} -> {"1":5,"2":6,"3":5,"4":5,"5":4,"6":6}（2人）；{"1":5,"2":5,"3":5,"4":5,"5":4,"6":5} -> {"1":5,"2":5,"3":4,"4":5,"5":4,"6":5}（1人） | 评价各商品名与'重新定义代谢健康，从而改变患者的生活方式、遇见更好的未来'产品理念的相关程度。 |
| C7 | C 商品名测试 | matrix_rating_1_7 | 9 | 0.9 | {"1":5,"2":5,"3":4,"4":5,"5":4,"6":5} -> {"1":5,"2":5,"3":5,"4":5,"5":4,"6":5}（2人）；{"1":5,"2":6,"3":5,"4":5,"5":4,"6":5} -> {"1":5,"2":6,"3":5,"4":5,"5":4,"6":6}（2人）；{"1":5,"2":5,"3":5,"4":5,"5":4,"6":5} -> {"1":5,"2":5,"3":4,"4":5,"5":4,"6":5}（1人） | 评价各商品名与'助力患者迈上通往健康的道路，自由前行'产品理念的相关程度。 |
| A20 | A 减重旅程 | multi | 8 | 0.8 | [1,2,3] -> [2,3]（1人）；[1,2] -> [1,2,3]（1人）；[1,2] -> [2,3]（1人） | 医生为您处方减重治疗方案中，包含以下哪些治疗方式？ |
| A8 | A 减重旅程 | matrix_rating_1_7 | 8 | 0.8 | {"1":4,"2":3,"3":0,"4":5} -> {"1":5,"2":3,"3":4,"4":6}（1人）；{"1":4,"2":3,"3":3,"4":5} -> {"1":4,"2":3,"3":0,"4":5}（1人）；{"1":4,"2":3,"3":4,"4":5} -> {"1":4,"2":3,"4":5}（1人） | 请您对这些非西医减重措施的减重效果满意度进行评价。 |
| D7 | D 受访者基本情况 | matrix_rating_1_7 | 8 | 0.8 | {"1":6,"2":6,"3":5,"4":5,"5":4,"6":7,"7":5,"8":5,"9":5,"10":6} -> {"1":6,"2":6,"3":5,"4":5,"5":4,"6":7,"7":5,"8":6,"9":5,"10":6}（1人）；{"1":6,"2":6,"3":5,"4":5,"5":4,"6":7,"7":5,"8":5,"9":5,"10":6} -> {"1":7,"2":7,"3":5,"4":5,"5":4,"6":7,"7":6,"8":6,"9":5,"10":6}（1人）；{"1":6,"2":6,"3":5,"4":5,"5":4,"6":7,"7":5,"8":5,"9":6,"10":6} -> {"1":7,"2":7,"3":6,"4":6,"5":4,"6":7,"7":5,"8":5,"9":7,"10":6}（1人） | 请对以下健康理念和身体状态表述的认同度打分。 |
| S10 | 甄别问卷 | multi | 8 | 0.8 | [2,3,4,5,9] -> [2,3,4,9,13]（1人）；[2,3,4,5,9] -> [2,4,9,12,13]（1人）；[2,3,4,9,10,12,13] -> [2,4,9,11]（1人） | 请问您既往经历过以下哪些减重方式？ |
| A10 | A 减重旅程 | multi | 7 | 0.7 | [3,4,5] -> [3,4,5]（2人）；[3,4,5] -> []（2人）；[2,4,7] -> [4,5,7]（1人） | 请问您未曾前往医院寻求减重方案的原因有哪些？ |
| A4a | A 减重旅程 | rank | 7 | 0.7 | {"1":1,"4":2,"2":3} -> {"1":1,"4":2,"2":3}（2人）；{"1":1,"4":2,"2":3} -> {"1":1,"4":2,"3":3}（2人）；{"1":1,"2":2,"4":3} -> {"1":1,"4":2,"2":3}（1人） | 在A4勾选的减重目标中，选出最重要的3项并排序。 |

## 8. Top变化问题逐人答案对照

| 题目ID | 问卷部分 | pid | 样本编号 | 年龄 | 性别 | BMI | BMI配额段 | 目标人群细分 | 合并症类别汇总 | 无背景答案 | 有背景答案 | 题目文本 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| A6 | A 减重旅程 | 411879101 | 120 | 55 | 男 | 24.22 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"2":{"attempts":3,"avg_months":6,"monthly_cost_rmb":200},"5":{"attempts":2,"avg_months":2,"monthly_cost_rmb":150},"9":{"attempts":4,"avg_months":4,"monthly_cost_rmb":0},"10":{"attempts":2,"avg_months":3,"monthly_cost_rmb":200},"1":{"attempts":1,"avg_months":1.5,"monthly_cost_rmb":300},"3":{"attempts":1,"avg_months":1,"monthly_cost_rmb":100}} | {"2":{"attempts":3,"avg_months":6,"monthly_cost_rmb":200},"4":{"attempts":2,"avg_months":3,"monthly_cost_rmb":300},"9":{"attempts":4,"avg_months":6,"monthly_cost_rmb":0},"10":{"attempts":2,"avg_months":4,"monthly_cost_rmb":100}} | 针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。 |
| A6 | A 减重旅程 | 420493101 | 123 | 45 | 男 | 24.51 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压；心脑血管 | {"2":{"attempts":3,"avg_months":6,"monthly_cost_rmb":300},"9":{"attempts":3,"avg_months":4,"monthly_cost_rmb":0},"10":{"attempts":2,"avg_months":3,"monthly_cost_rmb":200},"11":{"attempts":1,"avg_months":2,"monthly_cost_rmb":600},"1":{"attempts":1,"avg_months":1.5,"monthly_cost_rmb":400},"3":{"attempts":1,"avg_months":1,"monthly_cost_rmb":150}} | {"2":{"attempts":3,"avg_months":6,"monthly_cost_rmb":300},"4":{"attempts":2,"avg_months":3,"monthly_cost_rmb":200},"9":{"attempts":4,"avg_months":4,"monthly_cost_rmb":0},"10":{"attempts":2,"avg_months":2,"monthly_cost_rmb":200}} | 针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。 |
| A6 | A 减重旅程 | 673100701 | 138 | 34 | 男 | 24.84 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {"2":{"attempts":3,"avg_months":3,"monthly_cost_rmb":200},"4":{"attempts":2,"avg_months":2,"monthly_cost_rmb":300},"9":{"attempts":3,"avg_months":2,"monthly_cost_rmb":0},"10":{"attempts":1,"avg_months":1.5,"monthly_cost_rmb":200}} | {"2":{"attempts":3,"avg_months":3,"monthly_cost_rmb":300},"4":{"attempts":2,"avg_months":2,"monthly_cost_rmb":200},"9":{"attempts":3,"avg_months":2.5,"monthly_cost_rmb":0},"11":{"attempts":1,"avg_months":3,"monthly_cost_rmb":400}} | 针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。 |
| A6 | A 减重旅程 | 211769103 | 150 | 32 | 男 | 27.13 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 肝病或MASH线索 | {"2":{"attempts":3,"avg_months":4,"monthly_cost_rmb":300},"3":{"attempts":2,"avg_months":2,"monthly_cost_rmb":150},"4":{"attempts":1,"avg_months":1,"monthly_cost_rmb":200},"9":{"attempts":3,"avg_months":3,"monthly_cost_rmb":0},"12":{"attempts":1,"avg_months":2,"monthly_cost_rmb":400}} | {"2":{"attempts":3,"avg_months":3.0,"monthly_cost_rmb":300},"4":{"attempts":2,"avg_months":2.0,"monthly_cost_rmb":200},"9":{"attempts":3,"avg_months":2.0,"monthly_cost_rmb":0},"12":{"attempts":1,"avg_months":1.0,"monthly_cost_rmb":400},"13":{"attempts":1,"avg_months":3.0,"monthly_cost_rmb":1500}} | 针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。 |
| A6 | A 减重旅程 | 450250102 | 151 | 52 | 男 | 26.35 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {"2":{"attempts":3,"avg_months":6,"monthly_cost_rmb":200},"3":{"attempts":2,"avg_months":2,"monthly_cost_rmb":150},"9":{"attempts":4,"avg_months":6,"monthly_cost_rmb":0},"10":{"attempts":2,"avg_months":3,"monthly_cost_rmb":100}} | {"2":{"attempts":3,"avg_months":6,"monthly_cost_rmb":200},"3":{"attempts":2,"avg_months":2,"monthly_cost_rmb":150},"9":{"attempts":3,"avg_months":8,"monthly_cost_rmb":0},"10":{"attempts":1,"avg_months":3,"monthly_cost_rmb":100}} | 针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。 |
| A6 | A 减重旅程 | 411875101 | 187 | 47 | 男 | 26.73 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"2":{"attempts":4,"avg_months":6,"monthly_cost_rmb":300},"3":{"attempts":2,"avg_months":2,"monthly_cost_rmb":150},"4":{"attempts":2,"avg_months":3,"monthly_cost_rmb":200},"9":{"attempts":4,"avg_months":5,"monthly_cost_rmb":0},"10":{"attempts":2,"avg_months":2,"monthly_cost_rmb":200}} | {"2":{"attempts":3,"avg_months":6,"monthly_cost_rmb":300},"4":{"attempts":2,"avg_months":3,"monthly_cost_rmb":200},"9":{"attempts":4,"avg_months":4,"monthly_cost_rmb":0},"11":{"attempts":1,"avg_months":2,"monthly_cost_rmb":600}} | 针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。 |
| A6 | A 减重旅程 | 411313102 | 207 | 55 | 男 | 28.55 | 肥胖_BMI>28 | 肥胖且合并糖尿病 | 糖尿病 | {"2":{"attempts":3,"avg_months":6,"monthly_cost_rmb":200},"3":{"attempts":2,"avg_months":2,"monthly_cost_rmb":150},"4":{"attempts":2,"avg_months":3,"monthly_cost_rmb":200},"5":{"attempts":1,"avg_months":2,"monthly_cost_rmb":300},"9":{"attempts":4,"avg_months":6,"monthly_cost_rmb":0}} | {"2":{"attempts":3,"avg_months":6,"monthly_cost_rmb":200},"4":{"attempts":2,"avg_months":3,"monthly_cost_rmb":300},"9":{"attempts":4,"avg_months":6,"monthly_cost_rmb":0},"12":{"attempts":1,"avg_months":2,"monthly_cost_rmb":150},"13":{"attempts":1,"avg_months":4,"monthly_cost_rmb":800}} | 针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。 |
| A6 | A 减重旅程 | 220322103 | 47 | 32 | 女 | 28.04 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 关节运动系统 | {"2":{"attempts":4,"avg_months":3.0,"monthly_cost_rmb":300},"3":{"attempts":2,"avg_months":1.5,"monthly_cost_rmb":200},"4":{"attempts":2,"avg_months":2.0,"monthly_cost_rmb":300},"9":{"attempts":3,"avg_months":2.0,"monthly_cost_rmb":0}} | {"2":{"attempts":3,"avg_months":4,"monthly_cost_rmb":300},"3":{"attempts":2,"avg_months":2,"monthly_cost_rmb":200},"4":{"attempts":2,"avg_months":3,"monthly_cost_rmb":300},"9":{"attempts":2,"avg_months":3,"monthly_cost_rmb":0},"12":{"attempts":1,"avg_months":2,"monthly_cost_rmb":400}} | 针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。 |
| A6 | A 减重旅程 | 411244104 | 51 | 49 | 女 | 30.85 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {"2":{"attempts":4,"avg_months":6,"monthly_cost_rmb":200},"3":{"attempts":2,"avg_months":2,"monthly_cost_rmb":150},"4":{"attempts":2,"avg_months":3,"monthly_cost_rmb":200},"9":{"attempts":4,"avg_months":4,"monthly_cost_rmb":0},"11":{"attempts":1,"avg_months":3,"monthly_cost_rmb":400},"12":{"attempts":1,"avg_months":2,"monthly_cost_rmb":300}} | {"2":{"attempts":3,"avg_months":4.0,"monthly_cost_rmb":200},"3":{"attempts":2,"avg_months":2.0,"monthly_cost_rmb":100},"4":{"attempts":2,"avg_months":3.0,"monthly_cost_rmb":150},"9":{"attempts":3,"avg_months":3.0,"monthly_cost_rmb":0},"11":{"attempts":1,"avg_months":2.0,"monthly_cost_rmb":300}} | 针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。 |
| A6 | A 减重旅程 | 310855102 | 86 | 61 | 女 | 33.3 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {"2":{"attempts":4,"avg_months":6,"monthly_cost_rmb":200},"3":{"attempts":2,"avg_months":2,"monthly_cost_rmb":100},"4":{"attempts":2,"avg_months":3,"monthly_cost_rmb":150},"5":{"attempts":1,"avg_months":2,"monthly_cost_rmb":300},"9":{"attempts":3,"avg_months":4,"monthly_cost_rmb":0}} | {"2":{"attempts":3,"avg_months":6,"monthly_cost_rmb":200},"3":{"attempts":2,"avg_months":2,"monthly_cost_rmb":100},"4":{"attempts":2,"avg_months":3,"monthly_cost_rmb":150},"9":{"attempts":3,"avg_months":4,"monthly_cost_rmb":0}} | 针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。 |
| B10 | B GLP-1药物选择与使用情况 | 411879101 | 120 | 55 | 男 | 24.22 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"3":{"all_reasons":[5,4],"most_important":5}} |  | 既往使用过但目前已停用的GLP-1药物，停药原因分别是什么？最重要原因是什么？ |
| B10 | B GLP-1药物选择与使用情况 | 420493101 | 123 | 45 | 男 | 24.51 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压；心脑血管 |  | {"3":{"all_reasons":[2,4],"most_important":4}} | 既往使用过但目前已停用的GLP-1药物，停药原因分别是什么？最重要原因是什么？ |
| B10 | B GLP-1药物选择与使用情况 | 673100701 | 138 | 34 | 男 | 24.84 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {} | {"3":{"all_reasons":[4,5],"most_important":4}} | 既往使用过但目前已停用的GLP-1药物，停药原因分别是什么？最重要原因是什么？ |
| B10 | B GLP-1药物选择与使用情况 | 211769103 | 150 | 32 | 男 | 27.13 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 肝病或MASH线索 | {"3":{"all_reasons":[4,5],"most_important":4}} | {"3":{"all_reasons":[2,4],"most_important":4}} | 既往使用过但目前已停用的GLP-1药物，停药原因分别是什么？最重要原因是什么？ |
| B10 | B GLP-1药物选择与使用情况 | 450250102 | 151 | 52 | 男 | 26.35 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 |  | {"3":{"all_reasons":[5,4],"most_important":5}} | 既往使用过但目前已停用的GLP-1药物，停药原因分别是什么？最重要原因是什么？ |
| B10 | B GLP-1药物选择与使用情况 | 411875101 | 187 | 47 | 男 | 26.73 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"3":{"all_reasons":[4,5],"most_important":4}} | {"3":{"all_reasons":[2,4,5],"most_important":4}} | 既往使用过但目前已停用的GLP-1药物，停药原因分别是什么？最重要原因是什么？ |
| B10 | B GLP-1药物选择与使用情况 | 220322103 | 47 | 32 | 女 | 28.04 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 关节运动系统 | {} |  | 既往使用过但目前已停用的GLP-1药物，停药原因分别是什么？最重要原因是什么？ |
| B10 | B GLP-1药物选择与使用情况 | 411244104 | 51 | 49 | 女 | 30.85 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {"3":{"all_reasons":[2,4],"most_important":4}} | {} | 既往使用过但目前已停用的GLP-1药物，停药原因分别是什么？最重要原因是什么？ |
| B10 | B GLP-1药物选择与使用情况 | 310855102 | 86 | 61 | 女 | 33.3 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {} | {"3":{"all_reasons":[2,4,5],"most_important":4}} | 既往使用过但目前已停用的GLP-1药物，停药原因分别是什么？最重要原因是什么？ |
| B13 | B GLP-1药物选择与使用情况 | 411879101 | 120 | 55 | 男 | 24.22 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"A":[1,2,6,7,15]} |  | 选择相关GLP-1时，您从哪些信息渠道获取过产品信息？ |
| B13 | B GLP-1药物选择与使用情况 | 420493101 | 123 | 45 | 男 | 24.51 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压；心脑血管 | {"A":[1,4,7,8,15]} | {"A":[1,5,7,8,15]} | 选择相关GLP-1时，您从哪些信息渠道获取过产品信息？ |
| B13 | B GLP-1药物选择与使用情况 | 673100701 | 138 | 34 | 男 | 24.84 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {} | {"A":[1,5,7,8,15]} | 选择相关GLP-1时，您从哪些信息渠道获取过产品信息？ |
| B13 | B GLP-1药物选择与使用情况 | 211769103 | 150 | 32 | 男 | 27.13 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 肝病或MASH线索 | {"A":[1,2,5,6,7,15]} | {"A":[1,5,7,8,15]} | 选择相关GLP-1时，您从哪些信息渠道获取过产品信息？ |
| B13 | B GLP-1药物选择与使用情况 | 450250102 | 151 | 52 | 男 | 26.35 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {"A":[1,2,6,7,15]} | {"A":[1,2,7]} | 选择相关GLP-1时，您从哪些信息渠道获取过产品信息？ |
| B13 | B GLP-1药物选择与使用情况 | 411313102 | 207 | 55 | 男 | 28.55 | 肥胖_BMI>28 | 肥胖且合并糖尿病 | 糖尿病 | {"A":[1,2,5,7,15]} | {"A":[1,2,6,7,15]} | 选择相关GLP-1时，您从哪些信息渠道获取过产品信息？ |
| B13 | B GLP-1药物选择与使用情况 | 220322103 | 47 | 32 | 女 | 28.04 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 关节运动系统 | {} | {"A":[1,2,4,7,8,15]} | 选择相关GLP-1时，您从哪些信息渠道获取过产品信息？ |
| B13 | B GLP-1药物选择与使用情况 | 411244104 | 51 | 49 | 女 | 30.85 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {"A":[1,2,7,8,15]} | {} | 选择相关GLP-1时，您从哪些信息渠道获取过产品信息？ |
| B13 | B GLP-1药物选择与使用情况 | 310855102 | 86 | 61 | 女 | 33.3 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {} | {"A":[1,2,5,6,7,15]} | 选择相关GLP-1时，您从哪些信息渠道获取过产品信息？ |
| B14 | B GLP-1药物选择与使用情况 | 411879101 | 120 | 55 | 男 | 24.22 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":8,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":16}} |  | 回忆GLP-1实际使用过程中的剂量调整过程：起始剂量、维持剂量、过渡剂量及各阶段持续周数。 |
| B14 | B GLP-1药物选择与使用情况 | 420493101 | 123 | 45 | 男 | 24.51 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压；心脑血管 | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1mg","maintenance_weeks":8,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":16}} | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":20,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":28}} | 回忆GLP-1实际使用过程中的剂量调整过程：起始剂量、维持剂量、过渡剂量及各阶段持续周数。 |
| B14 | B GLP-1药物选择与使用情况 | 673100701 | 138 | 34 | 男 | 24.84 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {} | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":16,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":24}} | 回忆GLP-1实际使用过程中的剂量调整过程：起始剂量、维持剂量、过渡剂量及各阶段持续周数。 |
| B14 | B GLP-1药物选择与使用情况 | 211769103 | 150 | 32 | 男 | 27.13 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 肝病或MASH线索 | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1mg","maintenance_weeks":8,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":16}} | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":12,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":20}} | 回忆GLP-1实际使用过程中的剂量调整过程：起始剂量、维持剂量、过渡剂量及各阶段持续周数。 |
| B14 | B GLP-1药物选择与使用情况 | 411875101 | 187 | 47 | 男 | 26.73 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":16,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":24}} | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":20,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":28}} | 回忆GLP-1实际使用过程中的剂量调整过程：起始剂量、维持剂量、过渡剂量及各阶段持续周数。 |
| B14 | B GLP-1药物选择与使用情况 | 411313102 | 207 | 55 | 男 | 28.55 | 肥胖_BMI>28 | 肥胖且合并糖尿病 | 糖尿病 | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":12,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":20}} | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1mg","maintenance_weeks":8,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":16}} | 回忆GLP-1实际使用过程中的剂量调整过程：起始剂量、维持剂量、过渡剂量及各阶段持续周数。 |
| B14 | B GLP-1药物选择与使用情况 | 220322103 | 47 | 32 | 女 | 28.04 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 关节运动系统 | {} | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":8,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":16}} | 回忆GLP-1实际使用过程中的剂量调整过程：起始剂量、维持剂量、过渡剂量及各阶段持续周数。 |
| B14 | B GLP-1药物选择与使用情况 | 411244104 | 51 | 49 | 女 | 30.85 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1mg","maintenance_weeks":12,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":20}} | {} | 回忆GLP-1实际使用过程中的剂量调整过程：起始剂量、维持剂量、过渡剂量及各阶段持续周数。 |
| B14 | B GLP-1药物选择与使用情况 | 310855102 | 86 | 61 | 女 | 33.3 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {} | {"A":{"start_dose":"0.25mg","start_weeks":4,"maintenance_dose":"1.0mg","maintenance_weeks":16,"transition_doses":[{"dose":"0.5mg","weeks":4}],"total_weeks":24}} | 回忆GLP-1实际使用过程中的剂量调整过程：起始剂量、维持剂量、过渡剂量及各阶段持续周数。 |
| B16 | B GLP-1药物选择与使用情况 | 411879101 | 120 | 55 | 男 | 24.22 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"A":{"used_tool":2,"satisfaction":"","most_helpful_feature":""}} |  | 是否借助厂家提供的小程序作为用药记录、提醒和指南支持工具？满意度如何？最有帮助的功能是什么？ |
| B16 | B GLP-1药物选择与使用情况 | 420493101 | 123 | 45 | 男 | 24.51 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压；心脑血管 | {"A":{"used_tool":1,"satisfaction":6,"most_helpful_feature":"用药提醒和记录体重变化的功能"}} | {"A":{"used_tool":1,"satisfaction":6,"most_helpful_feature":"用药提醒和记录体重变化的功能比较有帮助。"}} | 是否借助厂家提供的小程序作为用药记录、提醒和指南支持工具？满意度如何？最有帮助的功能是什么？ |
| B16 | B GLP-1药物选择与使用情况 | 673100701 | 138 | 34 | 男 | 24.84 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {} | {"A":{"used_tool":2,"satisfaction":"","most_helpful_feature":""}} | 是否借助厂家提供的小程序作为用药记录、提醒和指南支持工具？满意度如何？最有帮助的功能是什么？ |
| B16 | B GLP-1药物选择与使用情况 | 450250102 | 151 | 52 | 男 | 26.35 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {"A":{"used_tool":2,"satisfaction":"","most_helpful_feature":""}} | {"A":{"used_tool":2,"satisfaction":"","most_helpful_feature":""},"B":{"used_tool":2,"satisfaction":"","most_helpful_feature":""},"C":{"used_tool":2,"satisfaction":"","most_helpful_feature":""}} | 是否借助厂家提供的小程序作为用药记录、提醒和指南支持工具？满意度如何？最有帮助的功能是什么？ |
| B16 | B GLP-1药物选择与使用情况 | 411875101 | 187 | 47 | 男 | 26.73 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"A":{"used_tool":2,"satisfaction":"","most_helpful_feature":""}} | {"A":{"used_tool":2,"satisfaction":"","most_helpful_feature":""},"B":{"used_tool":2,"satisfaction":"","most_helpful_feature":""},"C":{"used_tool":2,"satisfaction":"","most_helpful_feature":""}} | 是否借助厂家提供的小程序作为用药记录、提醒和指南支持工具？满意度如何？最有帮助的功能是什么？ |
| B16 | B GLP-1药物选择与使用情况 | 411313102 | 207 | 55 | 男 | 28.55 | 肥胖_BMI>28 | 肥胖且合并糖尿病 | 糖尿病 | {"A":{"used_tool":1,"satisfaction":6,"most_helpful_feature":"用药提醒和记录体重、血糖变化"}} | {"A":{"used_tool":2,"satisfaction":null,"most_helpful_feature":null},"B":{"used_tool":2,"satisfaction":null,"most_helpful_feature":null},"C":{"used_tool":2,"satisfaction":null,"most_helpful_feature":null}} | 是否借助厂家提供的小程序作为用药记录、提醒和指南支持工具？满意度如何？最有帮助的功能是什么？ |
| B16 | B GLP-1药物选择与使用情况 | 220322103 | 47 | 32 | 女 | 28.04 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 关节运动系统 | {} | {"A":{"used_tool":1,"satisfaction":6,"most_helpful_feature":"打针提醒和记录体重变化的功能"},"B":{"used_tool":2,"satisfaction":"","most_helpful_feature":""},"C":{"used_tool":2,"satisfaction":"","most_helpful_feature":""}} | 是否借助厂家提供的小程序作为用药记录、提醒和指南支持工具？满意度如何？最有帮助的功能是什么？ |
| B16 | B GLP-1药物选择与使用情况 | 411244104 | 51 | 49 | 女 | 30.85 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {"A":{"used_tool":2,"satisfaction":"","most_helpful_feature":""}} | {} | 是否借助厂家提供的小程序作为用药记录、提醒和指南支持工具？满意度如何？最有帮助的功能是什么？ |
| B16 | B GLP-1药物选择与使用情况 | 310855102 | 86 | 61 | 女 | 33.3 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {} | {"A":{"used_tool":2,"satisfaction":"","most_helpful_feature":""}} | 是否借助厂家提供的小程序作为用药记录、提醒和指南支持工具？满意度如何？最有帮助的功能是什么？ |
| B17 | B GLP-1药物选择与使用情况 | 411879101 | 120 | 55 | 男 | 24.22 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"3":{"loss_kg":5}} |  | 使用各GLP-1药物后，体重下降了多少kg？ |
| B17 | B GLP-1药物选择与使用情况 | 420493101 | 123 | 45 | 男 | 24.51 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压；心脑血管 | {"3":{"loss_kg":5}} | {"3":{"loss_kg":6}} | 使用各GLP-1药物后，体重下降了多少kg？ |
| B17 | B GLP-1药物选择与使用情况 | 673100701 | 138 | 34 | 男 | 24.84 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {} | {"3":{"loss_kg":6}} | 使用各GLP-1药物后，体重下降了多少kg？ |
| B17 | B GLP-1药物选择与使用情况 | 450250102 | 151 | 52 | 男 | 26.35 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {"3":{"loss_kg":5}} | {"1":{"loss_kg":""},"2":{"loss_kg":""},"3":{"loss_kg":5},"4":{"loss_kg":""},"5":{"loss_kg":""},"6":{"loss_kg":""}} | 使用各GLP-1药物后，体重下降了多少kg？ |
| B17 | B GLP-1药物选择与使用情况 | 411875101 | 187 | 47 | 男 | 26.73 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"3":{"loss_kg":6}} | {"1":{"loss_kg":""},"2":{"loss_kg":""},"3":{"loss_kg":6},"4":{"loss_kg":""},"5":{"loss_kg":""},"6":{"loss_kg":""}} | 使用各GLP-1药物后，体重下降了多少kg？ |
| B17 | B GLP-1药物选择与使用情况 | 411313102 | 207 | 55 | 男 | 28.55 | 肥胖_BMI>28 | 肥胖且合并糖尿病 | 糖尿病 | {"3":{"loss_kg":6}} | {"1":{"loss_kg":0},"2":{"loss_kg":0},"3":{"loss_kg":6},"4":{"loss_kg":0},"5":{"loss_kg":0},"6":{"loss_kg":0}} | 使用各GLP-1药物后，体重下降了多少kg？ |
| B17 | B GLP-1药物选择与使用情况 | 220322103 | 47 | 32 | 女 | 28.04 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 关节运动系统 | {} | {"3":{"loss_kg":6}} | 使用各GLP-1药物后，体重下降了多少kg？ |
| B17 | B GLP-1药物选择与使用情况 | 411244104 | 51 | 49 | 女 | 30.85 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {"3":{"loss_kg":7}} | {} | 使用各GLP-1药物后，体重下降了多少kg？ |
| B17 | B GLP-1药物选择与使用情况 | 310855102 | 86 | 61 | 女 | 33.3 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {} | {"3":{"loss_kg":6}} | 使用各GLP-1药物后，体重下降了多少kg？ |
| B18 | B GLP-1药物选择与使用情况 | 411879101 | 120 | 55 | 男 | 24.22 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"3":{"rebounded":2,"rebound_kg":""}} |  | 停止使用各GLP-1药物后，是否经历体重反弹？若经历，反弹多少kg？ |
| B18 | B GLP-1药物选择与使用情况 | 420493101 | 123 | 45 | 男 | 24.51 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压；心脑血管 |  | {"3":{"rebounded":1,"rebound_kg":2}} | 停止使用各GLP-1药物后，是否经历体重反弹？若经历，反弹多少kg？ |
| B18 | B GLP-1药物选择与使用情况 | 673100701 | 138 | 34 | 男 | 24.84 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {} | {"3":{"rebounded":1,"rebound_kg":3}} | 停止使用各GLP-1药物后，是否经历体重反弹？若经历，反弹多少kg？ |
| B18 | B GLP-1药物选择与使用情况 | 211769103 | 150 | 32 | 男 | 27.13 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 肝病或MASH线索 | {"3":{"rebounded":1,"rebound_kg":2}} | {"3":{"rebounded":1,"rebound_kg":3}} | 停止使用各GLP-1药物后，是否经历体重反弹？若经历，反弹多少kg？ |
| B18 | B GLP-1药物选择与使用情况 | 450250102 | 151 | 52 | 男 | 26.35 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 |  | {"3":{"rebounded":1,"rebound_kg":2}} | 停止使用各GLP-1药物后，是否经历体重反弹？若经历，反弹多少kg？ |
| B18 | B GLP-1药物选择与使用情况 | 411875101 | 187 | 47 | 男 | 26.73 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"3":{"rebounded":1,"rebound_kg":2}} | {"3":{"rebounded":1,"rebound_kg":3}} | 停止使用各GLP-1药物后，是否经历体重反弹？若经历，反弹多少kg？ |
| B18 | B GLP-1药物选择与使用情况 | 220322103 | 47 | 32 | 女 | 28.04 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 关节运动系统 | {} |  | 停止使用各GLP-1药物后，是否经历体重反弹？若经历，反弹多少kg？ |
| B18 | B GLP-1药物选择与使用情况 | 411244104 | 51 | 49 | 女 | 30.85 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {"3":{"rebounded":1,"rebound_kg":3}} | {} | 停止使用各GLP-1药物后，是否经历体重反弹？若经历，反弹多少kg？ |
| B18 | B GLP-1药物选择与使用情况 | 310855102 | 86 | 61 | 女 | 33.3 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {} | {"3":{"rebounded":1,"rebound_kg":3}} | 停止使用各GLP-1药物后，是否经历体重反弹？若经历，反弹多少kg？ |
| B19 | B GLP-1药物选择与使用情况 | 411879101 | 120 | 55 | 男 | 24.22 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"A":{"0":6,"1":6,"2":6,"3":5,"4":6,"5":5,"6":7,"7":6,"8":5,"9":6,"10":5,"11":5,"12":5,"13":6,"14":5,"15":7,"16":7,"17":3,"18":5,"19":4,"20":3}} |  | 结合实际使用体验，对使用过的GLP-1药物在各维度表现的满意度打分。 |
| B19 | B GLP-1药物选择与使用情况 | 420493101 | 123 | 45 | 男 | 24.51 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压；心脑血管 | {"A":{"0":6,"1":6,"2":6,"3":5,"4":4,"5":5,"6":6,"7":5,"8":5,"9":6,"10":5,"11":5,"12":5,"13":6,"14":5,"15":6,"16":6,"17":4,"18":5,"19":4,"20":3}} | {"A":{"0":6,"1":6,"2":7,"3":5,"4":3,"5":5,"6":6,"7":5,"8":4,"9":6,"10":5,"11":4,"12":5,"13":6,"14":5,"15":6,"16":7,"17":3,"18":5,"19":4,"20":3}} | 结合实际使用体验，对使用过的GLP-1药物在各维度表现的满意度打分。 |
| B19 | B GLP-1药物选择与使用情况 | 673100701 | 138 | 34 | 男 | 24.84 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {} | {"A":{"0":5,"1":5,"2":6,"3":4,"4":3,"5":4,"6":4,"7":4,"8":4,"9":5,"10":5,"11":4,"12":4,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":4,"20":3}} | 结合实际使用体验，对使用过的GLP-1药物在各维度表现的满意度打分。 |
| B19 | B GLP-1药物选择与使用情况 | 211769103 | 150 | 32 | 男 | 27.13 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 肝病或MASH线索 | {"A":{"0":5,"1":5,"2":6,"3":4,"4":3,"5":5,"6":5,"7":5,"8":4,"9":5,"10":5,"11":4,"12":4,"13":6,"14":5,"15":6,"16":6,"17":3,"18":5,"19":4,"20":3}} | {"A":{"0":5,"1":5,"2":6,"3":4,"4":3,"5":5,"6":6,"7":5,"8":4,"9":5,"10":5,"11":4,"12":4,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":4,"20":3}} | 结合实际使用体验，对使用过的GLP-1药物在各维度表现的满意度打分。 |
| B19 | B GLP-1药物选择与使用情况 | 450250102 | 151 | 52 | 男 | 26.35 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {"A":{"0":6,"1":6,"2":6,"3":5,"4":5,"5":5,"6":5,"7":5,"8":5,"9":6,"10":5,"11":5,"12":5,"13":6,"14":5,"15":6,"16":6,"17":4,"18":5,"19":4,"20":3}} | {"A":{"0":6,"1":6,"2":6,"3":5,"4":4,"5":5,"6":5,"7":5,"8":4,"9":5,"10":5,"11":5,"12":5,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":4,"20":3}} | 结合实际使用体验，对使用过的GLP-1药物在各维度表现的满意度打分。 |
| B19 | B GLP-1药物选择与使用情况 | 411875101 | 187 | 47 | 男 | 26.73 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"A":{"0":5,"1":5,"2":6,"3":4,"4":3,"5":5,"6":6,"7":5,"8":4,"9":5,"10":5,"11":4,"12":4,"13":6,"14":5,"15":6,"16":6,"17":4,"18":5,"19":4,"20":3}} | {"A":{"0":5,"1":5,"2":6,"3":4,"4":3,"5":5,"6":6,"7":5,"8":4,"9":5,"10":5,"11":4,"12":4,"13":6,"14":5,"15":6,"16":6,"17":3,"18":5,"19":4,"20":3}} | 结合实际使用体验，对使用过的GLP-1药物在各维度表现的满意度打分。 |
| B19 | B GLP-1药物选择与使用情况 | 411313102 | 207 | 55 | 男 | 28.55 | 肥胖_BMI>28 | 肥胖且合并糖尿病 | 糖尿病 | {"A":{"0":6,"1":6,"2":7,"3":5,"4":5,"5":6,"6":7,"7":6,"8":5,"9":6,"10":6,"11":4,"12":5,"13":6,"14":5,"15":6,"16":7,"17":4,"18":5,"19":4,"20":5}} | {"A":{"0":6,"1":6,"2":7,"3":5,"4":5,"5":6,"6":7,"7":6,"8":5,"9":6,"10":5,"11":5,"12":6,"13":6,"14":5,"15":6,"16":7,"17":4,"18":5,"19":4,"20":5}} | 结合实际使用体验，对使用过的GLP-1药物在各维度表现的满意度打分。 |
| B19 | B GLP-1药物选择与使用情况 | 220322103 | 47 | 32 | 女 | 28.04 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 关节运动系统 | {} | {"A":{"0":6,"1":6,"2":6,"3":5,"4":4,"5":5,"6":5,"7":5,"8":4,"9":6,"10":6,"11":4,"12":5,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":4,"20":3}} | 结合实际使用体验，对使用过的GLP-1药物在各维度表现的满意度打分。 |
| B19 | B GLP-1药物选择与使用情况 | 411244104 | 51 | 49 | 女 | 30.85 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {"A":{"0":5,"1":5,"2":6,"3":4,"4":3,"5":5,"6":5,"7":5,"8":4,"9":5,"10":5,"11":4,"12":4,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":4,"20":3}} | {} | 结合实际使用体验，对使用过的GLP-1药物在各维度表现的满意度打分。 |
| B19 | B GLP-1药物选择与使用情况 | 310855102 | 86 | 61 | 女 | 33.3 | 肥胖_BMI>28 | 肥胖未识别糖尿病 | 无可识别研究相关合并症 | {} | {"A":{"0":5,"1":5,"2":6,"3":4,"4":3,"5":5,"6":4,"7":4,"8":4,"9":5,"10":5,"11":4,"12":4,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":4,"20":3}} | 结合实际使用体验，对使用过的GLP-1药物在各维度表现的满意度打分。 |
| B3 | B GLP-1药物选择与使用情况 | 411879101 | 120 | 55 | 男 | 24.22 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"1":6,"2":7,"3":5,"4":6,"5":5,"6":7,"7":6,"8":5,"9":6,"10":4,"11":6,"12":6,"13":5,"14":5,"15":6,"16":7,"17":3,"18":5,"19":6,"20":5} | {"1":6,"2":7,"3":5,"4":6,"5":5,"6":7,"7":6,"8":5,"9":6,"10":4,"11":6,"12":6,"13":5,"14":5,"15":5,"16":6,"17":3,"18":5,"19":6,"20":5} | 选择GLP-1作为减重治疗药物时，以下考虑因素的重要程度分别如何？ |
| B3 | B GLP-1药物选择与使用情况 | 420493101 | 123 | 45 | 男 | 24.51 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压；心脑血管 | {"1":6,"2":7,"3":5,"4":6,"5":5,"6":7,"7":6,"8":5,"9":6,"10":5,"11":6,"12":6,"13":6,"14":5,"15":6,"16":6,"17":4,"18":5,"19":5,"20":4} | {"1":6,"2":7,"3":5,"4":6,"5":5,"6":7,"7":6,"8":5,"9":6,"10":4,"11":6,"12":6,"13":5,"14":5,"15":6,"16":7,"17":3,"18":6,"19":5,"20":4} | 选择GLP-1作为减重治疗药物时，以下考虑因素的重要程度分别如何？ |
| B3 | B GLP-1药物选择与使用情况 | 211769103 | 150 | 32 | 男 | 27.13 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 肝病或MASH线索 | {"1":6,"2":7,"3":5,"4":6,"5":5,"6":6,"7":6,"8":5,"9":6,"10":4,"11":6,"12":6,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":6,"20":5} | {"1":6,"2":7,"3":5,"4":6,"5":5,"6":6,"7":6,"8":5,"9":6,"10":5,"11":5,"12":5,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":5,"20":4} | 选择GLP-1作为减重治疗药物时，以下考虑因素的重要程度分别如何？ |
| B3 | B GLP-1药物选择与使用情况 | 450250102 | 151 | 52 | 男 | 26.35 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 关节运动系统 | {"1":6,"2":7,"3":5,"4":6,"5":5,"6":6,"7":6,"8":5,"9":6,"10":5,"11":6,"12":6,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":6,"20":5} | {"1":6,"2":7,"3":5,"4":6,"5":5,"6":6,"7":6,"8":4,"9":6,"10":5,"11":6,"12":6,"13":5,"14":5,"15":5,"16":6,"17":4,"18":5,"19":5,"20":4} | 选择GLP-1作为减重治疗药物时，以下考虑因素的重要程度分别如何？ |
| B3 | B GLP-1药物选择与使用情况 | 411875101 | 187 | 47 | 男 | 26.73 | 超重_24<BMI≤28 | 超重且有可识别合并症 | 高血压 | {"1":6,"2":7,"3":5,"4":6,"5":5,"6":7,"7":6,"8":5,"9":6,"10":5,"11":6,"12":6,"13":5,"14":5,"15":6,"16":6,"17":4,"18":5,"19":5,"20":4} | {"1":6,"2":7,"3":5,"4":6,"5":5,"6":7,"7":6,"8":5,"9":6,"10":4,"11":7,"12":7,"13":6,"14":5,"15":6,"16":6,"17":3,"18":5,"19":6,"20":5} | 选择GLP-1作为减重治疗药物时，以下考虑因素的重要程度分别如何？ |
| B3 | B GLP-1药物选择与使用情况 | 411313102 | 207 | 55 | 男 | 28.55 | 肥胖_BMI>28 | 肥胖且合并糖尿病 | 糖尿病 | {"1":6,"2":7,"3":6,"4":6,"5":5,"6":7,"7":6,"8":5,"9":6,"10":5,"11":5,"12":6,"13":6,"14":5,"15":6,"16":7,"17":4,"18":5,"19":5,"20":6} | {"1":6,"2":7,"3":6,"4":6,"5":5,"6":7,"7":6,"8":5,"9":6,"10":5,"11":5,"12":6,"13":5,"14":5,"15":5,"16":7,"17":4,"18":5,"19":5,"20":6} | 选择GLP-1作为减重治疗药物时，以下考虑因素的重要程度分别如何？ |

In [1]:
from pathlib import Path
import html
import pandas as pd
from IPython.display import HTML, display

RUN_DIR = Path(r'''C:\Users\siyid\workspace\silicon_sampling\obesity_patient_pipeline\data\obesity_questionnaire_10_persona_comparison_md_background''')
pd.set_option('display.unicode.east_asian_width', True)
pd.set_option('display.max_colwidth', 160)

combined = pd.read_csv(RUN_DIR / 'comparison_answers_combined.csv', dtype=str, keep_default_na=False)
diff = pd.read_csv(RUN_DIR / 'comparison_question_differences.csv', dtype=str, keep_default_na=False)
top_detail = pd.read_csv(RUN_DIR / 'comparison_top10_changed_answer_details.csv', dtype=str, keep_default_na=False)
persona_change = pd.read_csv(RUN_DIR / 'comparison_persona_change_counts.csv', dtype=str, keep_default_na=False)
demographics = pd.read_csv(RUN_DIR / 'comparison_selected_persona_demographics.csv', dtype=str, keep_default_na=False)
token_summary = pd.read_csv(RUN_DIR / 'comparison_runtime_token_summary.csv', dtype=str, keep_default_na=False)
combined.shape, diff.shape, top_detail.shape

((20, 98), (85, 11), (93, 20))

In [2]:
CJK_FONT_STACK = 'Microsoft YaHei, Microsoft JhengHei, SimHei, SimSun, Noto Sans CJK SC, PingFang SC, Arial, sans-serif'

def barh_svg(df, label_col, value_col, title, width=900):
    chart = df[[label_col, value_col]].copy()
    chart[value_col] = pd.to_numeric(chart[value_col], errors='coerce').fillna(0)
    chart = chart.sort_values(value_col, ascending=True)
    row_h, left, right, top = 30, 145, 40, 52
    height = top + row_h * len(chart) + 32
    plot_w = width - left - right
    max_value = max(float(chart[value_col].max()), 1.0)
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
             f'<rect width="{width}" height="{height}" fill="white"/>',
             f'<style>text{{font-family:{CJK_FONT_STACK};fill:#202124}} .title{{font-size:18px;font-weight:700}} .label{{font-size:13px}} .value{{font-size:12px;fill:#4b5563}}</style>',
             f'<text class="title" x="{left}" y="28">{html.escape(title)}</text>']
    for i, row in enumerate(chart.to_dict('records')):
        y = top + i * row_h
        value = float(row[value_col])
        bar_w = max(2, value / max_value * plot_w)
        label = html.escape(str(row[label_col]))
        parts += [f'<text class="label" x="{left-10}" y="{y+16}" text-anchor="end">{label}</text>',
                  f'<rect x="{left}" y="{y}" width="{bar_w:.1f}" height="18" rx="3" fill="#2563eb"/>',
                  f'<text class="value" x="{left+bar_w+6:.1f}" y="{y+14}">{value:g}</text>']
    parts.append('</svg>')
    return '\n'.join(parts)

display(HTML(barh_svg(diff.head(20), '题目ID', '答案变化人数', 'Top20题目：答案变化人数')))

In [3]:
display(HTML(barh_svg(persona_change.sort_values('变化题目数', ascending=False), '样本编号', '变化题目数', '每位persona受背景影响的题目数量')))

In [4]:
top_questions = diff.head(10)['题目ID'].tolist()
top_detail[top_detail['题目ID'].isin(top_questions)][['题目ID','问卷部分','题目文本','样本编号','年龄','性别','BMI','BMI配额段','目标人群细分','无背景答案','有背景答案']]

,题目ID,问卷部分,题目文本,样本编号,年龄,性别,BMI,BMI配额段,目标人群细分,无背景答案,有背景答案
0,A6,A 减重旅程,针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。,120,55,男,24.22,超重_24<BMI≤28,超重且有可识别合并症,"{""2"":{""attempts"":3,""avg_months"":6,""monthly_cost_rmb"":200},""5"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":150},""9"":{""attempts"":4,""avg_months"":4,""monthly...","{""2"":{""attempts"":3,""avg_months"":6,""monthly_cost_rmb"":200},""4"":{""attempts"":2,""avg_months"":3,""monthly_cost_rmb"":300},""9"":{""attempts"":4,""avg_months"":6,""monthly..."
1,A6,A 减重旅程,针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。,123,45,男,24.51,超重_24<BMI≤28,超重且有可识别合并症,"{""2"":{""attempts"":3,""avg_months"":6,""monthly_cost_rmb"":300},""9"":{""attempts"":3,""avg_months"":4,""monthly_cost_rmb"":0},""10"":{""attempts"":2,""avg_months"":3,""monthly_...","{""2"":{""attempts"":3,""avg_months"":6,""monthly_cost_rmb"":300},""4"":{""attempts"":2,""avg_months"":3,""monthly_cost_rmb"":200},""9"":{""attempts"":4,""avg_months"":4,""monthly..."
2,A6,A 减重旅程,针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。,138,34,男,24.84,超重_24<BMI≤28,超重且有可识别合并症,"{""2"":{""attempts"":3,""avg_months"":3,""monthly_cost_rmb"":200},""4"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":300},""9"":{""attempts"":3,""avg_months"":2,""monthly...","{""2"":{""attempts"":3,""avg_months"":3,""monthly_cost_rmb"":300},""4"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":200},""9"":{""attempts"":3,""avg_months"":2.5,""month..."
3,A6,A 减重旅程,针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。,150,32,男,27.13,超重_24<BMI≤28,超重且有可识别合并症,"{""2"":{""attempts"":3,""avg_months"":4,""monthly_cost_rmb"":300},""3"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":150},""4"":{""attempts"":1,""avg_months"":1,""monthly...","{""2"":{""attempts"":3,""avg_months"":3.0,""monthly_cost_rmb"":300},""4"":{""attempts"":2,""avg_months"":2.0,""monthly_cost_rmb"":200},""9"":{""attempts"":3,""avg_months"":2.0,""m..."
4,A6,A 减重旅程,针对经历过的非西医减重措施，分别填写尝试次数、单次平均坚持时长和月均花费。,151,52,男,26.35,超重_24<BMI≤28,超重且有可识别合并症,"{""2"":{""attempts"":3,""avg_months"":6,""monthly_cost_rmb"":200},""3"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":150},""9"":{""attempts"":4,""avg_months"":6,""monthly...","{""2"":{""attempts"":3,""avg_months"":6,""monthly_cost_rmb"":200},""3"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":150},""9"":{""attempts"":3,""avg_months"":8,""monthly..."
...,...,...,...,...,...,...,...,...,...,...,...
88,C1,C 新产品测试,阅读产品X、产品A、产品B、产品C信息后，对各药物在各维度上的表现满意度和总体满意度分别打分。,187,47,男,26.73,超重_24<BMI≤28,超重且有可识别合并症,"{""X"":{""1"":5,""2"":5,""3"":5,""4"":6,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":7,""4"":7,""5"":4,""6"":7},""B"":{""1"":6,""2"":6,""3"":5,""4"":6,""5"":4,""6"":6},""C"":{""1"":5,""2"":6,""3"":6,""4"":6,...","{""X"":{""1"":5,""2"":5,""3"":5,""4"":6,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":7,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":6,""3"":5,""4"":5,""5"":4,""6"":6},""C"":{""1"":6,""2"":5,""3"":6,""4"":5,..."
89,C1,C 新产品测试,阅读产品X、产品A、产品B、产品C信息后，对各药物在各维度上的表现满意度和总体满意度分别打分。,207,55,男,28.55,肥胖_BMI>28,肥胖且合并糖尿病,"{""X"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":3,""6"":5},""A"":{""1"":7,""2"":6,""3"":7,""4"":7,""5"":4,""6"":7},""B"":{""1"":6,""2"":6,""3"":5,""4"":6,""5"":4,""6"":6},""C"":{""1"":6,""2"":6,""3"":6,""4"":6,...","{""X"":{""1"":5,""2"":5,""3"":5,""4"":6,""5"":4,""6"":5},""A"":{""1"":7,""2"":5,""3"":7,""4"":7,""5"":4,""6"":7},""B"":{""1"":6,""2"":5,""3"":5,""4"":6,""5"":5,""6"":6},""C"":{""1"":6,""2"":5,""3"":6,""4"":6,..."
90,C1,C 新产品测试,阅读产品X、产品A、产品B、产品C信息后，对各药物在各维度上的表现满意度和总体满意度分别打分。,47,32,女,28.04,肥胖_BMI>28,肥胖未识别糖尿病,"{""X"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":7,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":5,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":5,""2"":5,""3"":6,""4"":5,...","{""X"":{""1"":5,""2"":5,""3"":5,""4"":6,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":7,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":5,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":6,""2"":5,""3"":6,""4"":5,..."
91,C1,C 新产品测试,阅读产品X、产品A、产品B、产品C信息后，对各药物在各维度上的表现满意度和总体满意度分别打分。,51,49,女,30.85,肥胖_BMI>28,肥胖未识别糖尿病,"{""X"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":7,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":5,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":5,""2"":5,""3"":6,""4"":5,...","{""X"":{""1"":5,""2"":5,""3"":5,""4"":6,""5"":4,""6"":5},""A"":{""1"":6,""2"":5,""3"":6,""4"":6,""5"":4,""6"":6},""B"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":5,""6"":5},""C"":{""1"":5,""2"":5,""3"":6,""4"":5,..."
92,C1,C 新产品测试,阅读产品X、产品A、产品B、产品C信息后，对各药物在各维度上的表现满意度和总体满意度分别打分。,86,61,女,33.3,肥胖_BMI>28,肥胖未识别糖尿病,"{""X"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":6,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":6,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":5,""2"":5,""3"":5,""4"":5,...","{""X"":{""1"":5,""2"":5,""3"":5,""4"":6,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":6,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":5,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":6,""2"":5,""3"":6,""4"":6,..."

In [5]:
pair_summary = (top_detail.groupby(['题目ID','问卷部分','无背景答案','有背景答案'])
                .size().reset_index(name='人数')
                .sort_values(['题目ID','人数'], ascending=[True, False]))
pair_summary.head(80)

,题目ID,问卷部分,无背景答案,有背景答案,人数
0,A6,A 减重旅程,"{""2"":{""attempts"":3,""avg_months"":3,""monthly_cost_rmb"":200},""4"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":300},""9"":{""attempts"":3,""avg_months"":2,""monthly...","{""2"":{""attempts"":3,""avg_months"":3,""monthly_cost_rmb"":300},""4"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":200},""9"":{""attempts"":3,""avg_months"":2.5,""month...",1
1,A6,A 减重旅程,"{""2"":{""attempts"":3,""avg_months"":4,""monthly_cost_rmb"":300},""3"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":150},""4"":{""attempts"":1,""avg_months"":1,""monthly...","{""2"":{""attempts"":3,""avg_months"":3.0,""monthly_cost_rmb"":300},""4"":{""attempts"":2,""avg_months"":2.0,""monthly_cost_rmb"":200},""9"":{""attempts"":3,""avg_months"":2.0,""m...",1
2,A6,A 减重旅程,"{""2"":{""attempts"":3,""avg_months"":6,""monthly_cost_rmb"":200},""3"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":150},""4"":{""attempts"":2,""avg_months"":3,""monthly...","{""2"":{""attempts"":3,""avg_months"":6,""monthly_cost_rmb"":200},""4"":{""attempts"":2,""avg_months"":3,""monthly_cost_rmb"":300},""9"":{""attempts"":4,""avg_months"":6,""monthly...",1
3,A6,A 减重旅程,"{""2"":{""attempts"":3,""avg_months"":6,""monthly_cost_rmb"":200},""3"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":150},""9"":{""attempts"":4,""avg_months"":6,""monthly...","{""2"":{""attempts"":3,""avg_months"":6,""monthly_cost_rmb"":200},""3"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":150},""9"":{""attempts"":3,""avg_months"":8,""monthly...",1
4,A6,A 减重旅程,"{""2"":{""attempts"":3,""avg_months"":6,""monthly_cost_rmb"":200},""5"":{""attempts"":2,""avg_months"":2,""monthly_cost_rmb"":150},""9"":{""attempts"":4,""avg_months"":4,""monthly...","{""2"":{""attempts"":3,""avg_months"":6,""monthly_cost_rmb"":200},""4"":{""attempts"":2,""avg_months"":3,""monthly_cost_rmb"":300},""9"":{""attempts"":4,""avg_months"":6,""monthly...",1
...,...,...,...,...,...
75,C1,C 新产品测试,"{""X"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":6,""4"":6,""5"":4,""6"":6},""B"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":5,""2"":5,""3"":5,""4"":5,...","{""X"":{""1"":5,""2"":5,""3"":5,""4"":6,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":7,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":6,""3"":5,""4"":5,""5"":4,""6"":6},""C"":{""1"":6,""2"":5,""3"":6,""4"":5,...",1
76,C1,C 新产品测试,"{""X"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":6,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":6,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":5,""2"":5,""3"":5,""4"":5,...","{""X"":{""1"":5,""2"":5,""3"":5,""4"":6,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":6,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":5,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":6,""2"":5,""3"":6,""4"":6,...",1
77,C1,C 新产品测试,"{""X"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":7,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":5,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":5,""2"":5,""3"":6,""4"":5,...","{""X"":{""1"":5,""2"":5,""3"":5,""4"":6,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":7,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":5,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":6,""2"":5,""3"":6,""4"":5,...",1
78,C1,C 新产品测试,"{""X"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":7,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":5,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":5,""2"":5,""3"":6,""4"":5,...","{""X"":{""1"":5,""2"":5,""3"":5,""4"":6,""5"":4,""6"":5},""A"":{""1"":6,""2"":5,""3"":6,""4"":6,""5"":4,""6"":6},""B"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":5,""6"":5},""C"":{""1"":5,""2"":5,""3"":6,""4"":5,...",1
79,C1,C 新产品测试,"{""X"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":3,""6"":5},""A"":{""1"":6,""2"":5,""3"":7,""4"":6,""5"":4,""6"":6},""B"":{""1"":6,""2"":5,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":6,""2"":5,""3"":6,""4"":5,...","{""X"":{""1"":6,""2"":5,""3"":5,""4"":6,""5"":4,""6"":5},""A"":{""1"":6,""2"":5,""3"":6,""4"":6,""5"":4,""6"":6},""B"":{""1"":5,""2"":5,""3"":5,""4"":5,""5"":4,""6"":5},""C"":{""1"":6,""2"":5,""3"":5,""4"":5,...",1

In [6]:
persona_profile_cols = ['variant_label','pid','样本编号','目标人群细分','BMI配额段','persona_summary','response_style','assumption_notes']
combined[[c for c in persona_profile_cols if c in combined.columns]].sort_values(['pid','variant_label'])

,variant_label,pid,样本编号,目标人群细分,BMI配额段,persona_summary,response_style,assumption_notes
6,不含背景信息,211769103,150,超重且有可识别合并症,超重_24<BMI≤28,,,"[""S2 城市线级：CFPS仅有省份和城乡属性，无法精确映射城市线级，假设为三线城市（代码3），符合黑龙江省普通城镇受访者的常见分布。"",""S5A 家庭年收入：CFPS仅有个人就业收入44000元，按项目说明用其近似家庭收入，选择1.7-5万（代码3），假设家庭整体收入水平与个人接近。"",""S6 腰围95cm为..."
16,含背景信息,211769103,150,超重且有可识别合并症,超重_24<BMI≤28,,,"[""S2 城市线级：CFPS仅有省份和城乡属性，假设黑龙江省城镇为三线城市，选择代码3。"",""S5A 家庭年收入：CFPS仅有个人就业收入44000元，按题目选项合理假设家庭总收入为1.7-5万区间，对应代码3。"",""S6 腰围95cm为根据身高177cm、体重85kg的超重男性合理估计。"",""S8 合并症仅选..."
0,不含背景信息,220322103,47,肥胖未识别糖尿病,肥胖_BMI>28,,,"[""S2 城市线级：吉林省城镇，无法从CFPS精确映射，假设为三线城市（代码3），符合东北地级市常见线级。"",""S5A 家庭年收入：CFPS仅有个人月收入约20000元，推断家庭年收入为5-10万区间（代码2），保守不选10万以上。"",""S6 腰围：CFPS无腰围数据，基于158cm、70kg、轻度肥胖女性合理..."
10,含背景信息,220322103,47,肥胖未识别糖尿病,肥胖_BMI>28,,,"[""S2 城市线级：吉林省城镇，无法从CFPS精确映射，假设为三线城市（代码3），符合非省会地级市或中小城市的典型情况。"",""S5A 家庭年收入：CFPS仅有个人就业收入约20000元/月，近似推断家庭年收入为5-10万（代码2），考虑到可能与父母同住或伴侣收入不高。"",""S6 腰围90cm为合理估计，基于身高..."
2,不含背景信息,310855102,86,肥胖未识别糖尿病,肥胖_BMI>28,,,"[""S2 城市线级：根据省份为上海市且为城镇，合理归类为一线城市，选择代码1。"",""S5A 家庭年收入：CFPS仅有个人就业收入43200元，按题目选项保守推断家庭总收入落在1.7-5万区间，选择代码3。"",""S6 腰围：CFPS无腰围数据，结合BMI 33.3和61岁女性肥胖情况，合理假设腰围100cm。"",..."
12,含背景信息,310855102,86,肥胖未识别糖尿病,肥胖_BMI>28,,,"[""S2 城市线级：CFPS仅有省份和城乡属性，受访者在上海市城镇，合理假设为一线城市，填1。"",""S5A 家庭年收入：CFPS只有个人就业收入43200元，按筛选规则映射到1.7-5万区间，假设家庭总收入同区间，填3。"",""S6 腰围：CFPS无腰围数据，61岁女性、BMI 33.3，合理估计腰围约100cm..."
1,不含背景信息,411244104,51,肥胖未识别糖尿病,肥胖_BMI>28,,,"[""S2 城市线级：CFPS仅有河南省城镇信息，无法精确到城市线级，假设为三线城市（代码3），符合河南不少城镇分布。"",""S5A 家庭年收入：CFPS只有个人就业收入38400元，按题目要求用其近似家庭收入，落入1.7-5万区间（代码3），假设家庭整体收入水平与个人接近。"",""S6 腰围98cm为合理估计，基于..."
11,含背景信息,411244104,51,肥胖未识别糖尿病,肥胖_BMI>28,,,"[""S2 城市线级：CFPS仅有省份和城乡属性，无法精确映射城市线级。受访者位于河南省城镇，模拟为三线城市（代码3），符合非一二线大城市的可能性。"",""S5A 家庭年收入：CFPS仅有个人就业收入38400元，落在1.7万-5万区间。家庭总收入无法直接判定，假设家庭年收入也在1.7-5万区间（代码3），与个人收..."
9,不含背景信息,411313102,207,肥胖且合并糖尿病,肥胖_BMI>28,,,"[""S2 城市线级：根据河南省城镇、收入和职业，合理假设为三线城市，选择代码3。"",""S5A 家庭年收入：CFPS仅有个人就业收入60000元，假设家庭总收入落在5-10万区间，对应代码2。"",""S6 腰围：CFPS无腰围数据，结合170cm、82.5kg和轻度肥胖中年男性，保守估计为100cm。"",""S10 ..."
19,含背景信息,411313102,207,肥胖且合并糖尿病,肥胖_BMI>28,,,"[""S2 城市线级：河南省城镇但无具体城市，合理假设为三线城市，选择代码3。"",""S5A 家庭年收入：仅有个人年收入约6万，合理假设家庭总收入为5-10万区间，对应代码2。"",""S6 腰围：CFPS无腰围数据，结合55岁男性、BMI 28.55和轻度肥胖，保守估计腰围100cm。"",""S10 既往减重方式的具体..."
8,不含背景信息,411875101,187,超重且有可识别合并症,超重_24<BMI≤28,,,"[""S2 城市线级：CFPS仅有河南省城镇信息，无法精确到线级，假设为三线城市（代码3），符合河南不少地级市为三线的情况。"",""S5A 家庭年收入：CFPS给出个人就业收入约6.5万，假设家庭总收入落在5-10万区间（代码2），与个人收入水平相符且满足筛选要求。"",""S6 腰围92cm为合理估计，基于男性、17..."
18,含背景信息,411875101,187,超重且有可识别合并症,超重_24<BMI≤28,,,"[""S2 城市线级：CFPS仅有河南省城镇信息，无法精确映射城市线级，假设为三线城市（代码3），符合河南不少城镇分布。"",""S5A 家庭年收入：CFPS仅有个人就业收入65000元，按规则近似为家庭收入5-10万区间（代码2），假设家庭其他成员收入不高或为单职工家庭。"",""S6 腰围92cm为模拟值，基于男性、..."
3,不含背景信息,411879101,120,超重且有可识别合并症,超重_24<BMI≤28,,,"[""S2 城市线级：CFPS仅有河南省城镇信息，无法精确映射城市线级，假设为三线城市（代码3），符合河南不少地级市为三线的常见情况。"",""S5A 家庭年收入：CFPS提供个人就业收入85000元，作为家庭收入近似代理，按问卷档位选择5-10万（代码2），假设家庭其他成员收入不高或无固定收入。"",""S6 腰围92..."
13,含背景信息,411879101,120,超重且有可识别合并症,超重_24<BMI≤28,,,"[""S2 城市线级：CFPS仅有河南省城镇信息，无法精确到城市线级，假设为三线城市（代码3），符合河南不少地级市/县级市特征。"",""S5A 家庭年收入：CFPS给出个人就业收入85000元，作为家庭收入近似代理，按选项选择5-10万（代码2），假设家庭其他成员收入不高或为全家主要收入来源。"",""S6 腰围90c..."
4,不含背景信息,420493101,123,超重且有可识别合并症,超重_24<BMI≤28,,,"[""S2 城市线级：湖北省城镇，无法从CFPS精确映射，假定为二线城市（代码2），符合收入和工作单位特征。"",""S5A 家庭年收入：CFPS仅有个人就业收入约20万，合理推断家庭总收入为10万以上，选择代码1。"",""S6 腰围92cm为模拟值，结合男性超重且有高血压、冠心病风险的典型腰围水平。"",""S8 仅选择..."
14,含背景信息,420493101,123,超重且有可识别合并症,超重_24<BMI≤28,,,"[""S2 城市线级：CFPS仅有省份和城乡属性，无法精确到城市线级，基于湖北省城镇、收入和职业，合理假设为二线城市（代码2）。"",""S5A 家庭年收入：CFPS仅有个人就业收入204300元，按说明用其近似家庭收入，故选择“10万以上”（代码1）。"",""S6 腰围92cm为合理估计，结合45岁男性、BMI 24..."
7,不含背景信息,450250102,151,超重且有可识别合并症,超重_24<BMI≤28,,,"[""S2 城市线级=3为模拟推断：受访者位于广西城镇，结合省份整体发展水平，保守设定为三线城市。"",""S5A 家庭年收入=3(1.7-5万)为模拟推断：仅有个人就业收入27800元，按题目要求将其近似为家庭总收入区间下限段。"",""S6 腰围92cm为模拟推断：依据男性、BMI 26.35和超重状态合理估计。"",..."
17,含背景信息,450250102,151,超重且有可识别合并症,超重_24<BMI≤28,,,"[""S2 城市线级：CFPS仅有省份和城乡属性，无法精确映射城市线级。受访者为广西城镇，模拟为三线城市（代码3），符合多数地级市/县级市特征。"",""S5A 家庭年收入：CFPS仅有个人就业收入27800元，作为家庭收入近似代理，按题目选项选择1.7-5万（代码3），与筛选口径一致。"",""S6 腰围92cm为模拟..."
5,不含背景信息,673100701,138,超重且有可识别合并症,超重_24<BMI≤28,,,"[""S2 城市线级：CFPS仅有省份和城乡属性，受访者在山东省城镇，合理假设为二线城市（代码2）。"",""S5A 家庭年收入：CFPS只有个人就业收入49000元，按项目规则用作家庭收入近似，落在1.7-5万区间（代码3）。"",""S6 腰围95cm为基于超重男性、低频锻炼的合理估计。"",""S8 仅硬事实为关节运动..."
15,含背景信息,673100701,138,超重且有可识别合并症,超重_24<BMI≤28,,,"[""S2 城市线级：CFPS仅有山东省城镇信息，无法精确映射城市线级，假设为二线城市（代码2），符合山东部分地级市特征。"",""S5A 家庭年收入：CFPS仅有个人就业收入49000元，按题目要求用其近似家庭年收入，落入1.7-5万区间（代码3）。"",""S6 腰围95cm为合理估计，结合185cm、85kg、男性..."